# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x16\x65ven_connect.g2.common*\xf2\x01\n\neErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x07\n\x03\x43RC\x10\x01\x12\x0c\n\x08PKT_LOST\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x12\x10\n\x0cNO_RESOURCES\x10\x04\x12\x0c\n\x08PB_ERROR\x10\x05\x12\x08\n\x04NULL\x10\x06\x12\x08\n\x04\x46\x41IL\x10\x07\x12\x0f\n\x0bNOT_SUPPORT\x10\x08\x12\x0b\n\x07SUPPORT\x10\t\x12\x0b\n\x07HEAD_ID\x10\n\x12\x12\n\x0eINVALID_LENGTH\x10\x0b\x12\x10\n\x0cINVALID_SDID\x10\x0c\x12\x14\n\x10\x44UPLICATE_PACKET\x10\r\x12\x18\n\x14RING_CONNECT_TIMEOUT\x10Zb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EERRORCODE']._serialized_start=41
  _globals['_EERRORCODE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
