# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_settings.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'dev_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65v_settings.proto\x12\x1c\x65ven_connect.g2.dev_settings\x1a\x0c\x63ommon.proto\"\x84\x01\n\nAudControl\x12\x32\n\x03\x63md\x18\x01 \x01(\x0e\x32%.even_connect.g2.dev_settings.eAudCmd\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x32\n\x06result\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"c\n\x08TimeSync\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x10\n\x08timezone\x18\x02 \x01(\x03\x12\x32\n\x06result\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"G\n\x11\x42\x61seConnHeartBeat\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"B\n\x0cQuickRestart\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"D\n\x0eRestoreFactory\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode*g\n\x07\x65\x41udCmd\x12\x10\n\x0c\x41UD_CMD_NONE\x10\x00\x12\x10\n\x0c\x41UD_CMD_OPEN\x10\x01\x12\x11\n\rAUD_CMD_CLOSE\x10\x02\x12\x11\n\rAUD_CMD_PAUSE\x10\x03\x12\x12\n\x0e\x41UD_CMD_RESUME\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EAUDCMD']._serialized_start=513
  _globals['_EAUDCMD']._serialized_end=616
  _globals['_AUDCONTROL']._serialized_start=67
  _globals['_AUDCONTROL']._serialized_end=199
  _globals['_TIMESYNC']._serialized_start=201
  _globals['_TIMESYNC']._serialized_end=300
  _globals['_BASECONNHEARTBEAT']._serialized_start=302
  _globals['_BASECONNHEARTBEAT']._serialized_end=373
  _globals['_QUICKRESTART']._serialized_start=375
  _globals['_QUICKRESTART']._serialized_end=441
  _globals['_RESTOREFACTORY']._serialized_start=443
  _globals['_RESTOREFACTORY']._serialized_end=511
# @@protoc_insertion_point(module_scope)
