# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: efs_transmit.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'efs_transmit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x66s_transmit.proto\x12\x1c\x65ven_connect.g2.efs_transmit*k\n\x14\x65\x45venFileServiceType\x12\x1f\n\x1bNOTIFICATION_JSON_WHITELIST\x10\x00\x12!\n\x1d\x41NDROID_MSG_JSON_NOTIFICATION\x10\x01\x12\x0f\n\nOTHER_FILE\x10\xaa\x01*\xc8\x02\n\x13\x65\x45venFileServiceRsp\x12!\n\x1d\x45VEN_FILE_SERVICE_RSP_SUCCESS\x10\x00\x12#\n\x1f\x45VEN_FILE_SERVICE_RSP_START_ERR\x10\x01\x12&\n\"EVEN_FILE_SERVICE_RSP_DATA_CRC_ERR\x10\x02\x12)\n%EVEN_FILE_SERVICE_RSP_FLASH_WRITE_ERR\x10\x03\x12!\n\x1d\x45VEN_FILE_SERVICE_RSP_TIMEOUT\x10\x04\x12&\n\"EVEN_FILE_SERVICE_RSP_NO_RESOURCES\x10\x05\x12+\n\'EVEN_FILE_SERVICE_RSP_RESULT_CHECK_FAIL\x10\x06\x12\x1e\n\x1a\x45VEN_FILE_SERVICE_RSP_FAIL\x10\x07*\x99\x01\n\x19\x65\x45venFileExportServiceCID\x12&\n\"EVEN_FILE_SERVICE_CMD_EXPORT_START\x10\x00\x12%\n!EVEN_FILE_SERVICE_CMD_EXPORT_DATA\x10\x01\x12-\n)EVEN_FILE_SERVICE_CMD_EXPORT_RESULT_CHECK\x10\x02*\x91\x01\n\x17\x65\x45venFileSendServiceCID\x12$\n EVEN_FILE_SERVICE_CMD_SEND_START\x10\x00\x12#\n\x1f\x45VEN_FILE_SERVICE_CMD_SEND_DATA\x10\x01\x12+\n\'EVEN_FILE_SERVICE_CMD_SEND_RESULT_CHECK\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'efs_transmit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EEVENFILESERVICETYPE']._serialized_start=52
  _globals['_EEVENFILESERVICETYPE']._serialized_end=159
  _globals['_EEVENFILESERVICERSP']._serialized_start=162
  _globals['_EEVENFILESERVICERSP']._serialized_end=490
  _globals['_EEVENFILEEXPORTSERVICECID']._serialized_start=493
  _globals['_EEVENFILEEXPORTSERVICECID']._serialized_end=646
  _globals['_EEVENFILESENDSERVICECID']._serialized_start=649
  _globals['_EEVENFILESENDSERVICECID']._serialized_end=794
# @@protoc_insertion_point(module_scope)
