# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glasses_case.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'glasses_case.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12glasses_case.proto\x12\x1c\x65ven_connect.g2.glasses_case\x1a\x0c\x63ommon.proto\"\x94\x01\n\x0fGlassesCaseInfo\x12\x0b\n\x03soc\x18\x01 \x01(\x05\x12\x14\n\x0c\x63hargeStatus\x18\x02 \x01(\x05\x12\x11\n\tlidStatus\x18\x03 \x01(\x05\x12\x14\n\x0cinCaseStatus\x18\x04 \x01(\x05\x12\x35\n\terrorCode\x18\x05 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xc8\x01\n\x16GlassesCaseDataPackage\x12\x46\n\tcommandId\x18\x01 \x01(\x0e\x32\x33.even_connect.g2.glasses_case.eGlassesCaseCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x44\n\x08\x63\x61seInfo\x18\x03 \x01(\x0b\x32-.even_connect.g2.glasses_case.GlassesCaseInfoH\x00\x88\x01\x01\x42\x0b\n\t_caseInfo*8\n\x15\x65GlassesCaseCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\r\n\tCASE_INFO\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glasses_case_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EGLASSESCASECOMMANDID']._serialized_start=420
  _globals['_EGLASSESCASECOMMANDID']._serialized_end=476
  _globals['_GLASSESCASEINFO']._serialized_start=67
  _globals['_GLASSESCASEINFO']._serialized_end=215
  _globals['_GLASSESCASEDATAPACKAGE']._serialized_start=218
  _globals['_GLASSESCASEDATAPACKAGE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
