# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x16\x65ven_connect.g2.logger\"\x84\x03\n\x13logger_main_msg_ctx\x12\x34\n\x03\x63md\x18\x01 \x01(\x0e\x32\'.even_connect.g2.logger.logger_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x12\n\nbleTransEn\x18\x03 \x01(\x05\x12\x42\n\x08levelMsg\x18\x04 \x01(\x0b\x32+.even_connect.g2.logger.ble_trans_level_msgH\x00\x88\x01\x01\x12\x13\n\x06logStr\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x45\n\nrequestMsg\x18\x06 \x01(\x0b\x32,.even_connect.g2.logger.request_filelist_msgH\x02\x88\x01\x01\x12<\n\x06\x64\x65lMsg\x18\x07 \x01(\x0b\x32\'.even_connect.g2.logger.delete_file_msgH\x03\x88\x01\x01\x42\x0b\n\t_levelMsgB\t\n\x07_logStrB\r\n\x0b_requestMsgB\t\n\x07_delMsg\",\n\x13\x62le_trans_level_msg\x12\x15\n\rbleTransLevel\x18\x01 \x01(\x05\"5\n\x0f\x64\x65lete_file_msg\x12\x15\n\x08\x66ileName\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_fileName\"(\n\x14request_filelist_msg\x12\x10\n\x08\x66ileName\x18\x01 \x03(\t*\xc6\x01\n\x0flogger_Cmd_list\x12\x18\n\x14\x43ONNECT_HEART_PACKET\x10\x00\x12\x19\n\x15\x42LE_LOGGER_SWITCH_SET\x10\x01\x12\x18\n\x14\x42LE_LOGGER_LEVEL_SET\x10\x02\x12\x1b\n\x17\x44\x45VICE_SEND_LOGGER_DATA\x10\x03\x12\x15\n\x11REQUEST_FILE_NAME\x10\x04\x12\x14\n\x10\x44\x45LETE_FILE_NAME\x10\x05\x12\x1a\n\x16\x44\x45LETE_ALL_LOGGER_FILE\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGGER_CMD_LIST']._serialized_start=575
  _globals['_LOGGER_CMD_LIST']._serialized_end=773
  _globals['_LOGGER_MAIN_MSG_CTX']._serialized_start=41
  _globals['_LOGGER_MAIN_MSG_CTX']._serialized_end=429
  _globals['_BLE_TRANS_LEVEL_MSG']._serialized_start=431
  _globals['_BLE_TRANS_LEVEL_MSG']._serialized_end=475
  _globals['_DELETE_FILE_MSG']._serialized_start=477
  _globals['_DELETE_FILE_MSG']._serialized_end=530
  _globals['_REQUEST_FILELIST_MSG']._serialized_start=532
  _globals['_REQUEST_FILELIST_MSG']._serialized_end=572
# @@protoc_insertion_point(module_scope)
