# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: module_configure.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'module_configure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16module_configure.proto\x12 even_connect.g2.module_configure\"\xf2\x02\n\x1dmodule_configure_main_msg_ctx\x12H\n\x03\x63md\x18\x01 \x01(\x0e\x32;.even_connect.g2.module_configure.module_configure_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12]\n\x11SysGeneralSetting\x18\x03 \x01(\x0b\x32=.even_connect.g2.module_configure.send_system_general_settingH\x00\x88\x01\x01\x12\x61\n\x17\x44\x61shboardGeneralSetting\x18\x04 \x01(\x0b\x32;.even_connect.g2.module_configure.dashboard_general_settingH\x01\x88\x01\x01\x42\x14\n\x12_SysGeneralSettingB\x1a\n\x18_DashboardGeneralSetting\"3\n\x19\x64\x61shboard_general_setting\x12\x16\n\x0e\x61utoCloseValue\x18\x01 \x01(\x05\"4\n\x1bsend_system_general_setting\x12\x15\n\rlanguageIndex\x18\x01 \x01(\x05*\x92\x01\n\x19module_configure_Cmd_list\x12!\n\x1dSYSTEM_GENERAL_SETTING_PACKET\x10\x00\x12*\n&APP_INQUIRE_DASHBOARD_AUTO_CLOSE_VALUE\x10\x01\x12&\n\"APP_SET_DASHBOARD_AUTO_CLOSE_VALUE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'module_configure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULE_CONFIGURE_CMD_LIST']._serialized_start=541
  _globals['_MODULE_CONFIGURE_CMD_LIST']._serialized_end=687
  _globals['_MODULE_CONFIGURE_MAIN_MSG_CTX']._serialized_start=61
  _globals['_MODULE_CONFIGURE_MAIN_MSG_CTX']._serialized_end=431
  _globals['_DASHBOARD_GENERAL_SETTING']._serialized_start=433
  _globals['_DASHBOARD_GENERAL_SETTING']._serialized_end=484
  _globals['_SEND_SYSTEM_GENERAL_SETTING']._serialized_start=486
  _globals['_SEND_SYSTEM_GENERAL_SETTING']._serialized_end=538
# @@protoc_insertion_point(module_scope)
