# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x1c\x65ven_connect.g2.notification\x1a\x0c\x63ommon.proto\"l\n\x19NotificationWhitelistCtrl\x12\x18\n\x10whitelistDisable\x18\x01 \x01(\x05\x12\x35\n\terrorCode\x18\x02 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\x95\x01\n\x13NotificationCommRsp\x12G\n\tcommandId\x18\x01 \x01(\x0e\x32\x34.even_connect.g2.notification.eNotificationCommandId\x12\x35\n\terrorCode\x18\x02 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"l\n\x0fNotificationIOS\x12\r\n\x05\x61ppID\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\x0c\x12\x35\n\terrorCode\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xa7\x01\n\x13NotificationControl\x12\x13\n\x0bnotifEnable\x18\x01 \x01(\x05\x12\x16\n\x0e\x61utoDispEnable\x18\x02 \x01(\x05\x12\x10\n\x08\x64ispTime\x18\x03 \x01(\x05\x12\x35\n\terrorCode\x18\x04 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\x12\x1a\n\x12\x61voidDisturbEnable\x18\x05 \x01(\x05\"\xc5\x03\n\x17NotificationDataPackage\x12G\n\tcommandId\x18\x01 \x01(\x0e\x32\x34.even_connect.g2.notification.eNotificationCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x44\n\x04\x63trl\x18\x03 \x01(\x0b\x32\x31.even_connect.g2.notification.NotificationControlH\x00\x88\x01\x01\x12?\n\x03IOS\x18\x04 \x01(\x0b\x32-.even_connect.g2.notification.NotificationIOSH\x01\x88\x01\x01\x12\x44\n\x04resp\x18\x05 \x01(\x0b\x32\x31.even_connect.g2.notification.NotificationCommRspH\x02\x88\x01\x01\x12S\n\rwhitelistCtrl\x18\x06 \x01(\x0b\x32\x37.even_connect.g2.notification.NotificationWhitelistCtrlH\x03\x88\x01\x01\x42\x07\n\x05_ctrlB\x06\n\x04_IOSB\x07\n\x05_respB\x10\n\x0e_whitelistCtrl*\x94\x01\n\x16\x65NotificationCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\x15\n\x11NOTIFICATION_CTRL\x10\x01\x12\x14\n\x10NOTIFICATION_IOS\x10\x02\x12\x1f\n\x1bNOTIFICATION_WHITELIST_CTRL\x10\x03\x12\x1a\n\x15NOTIFICATION_COMM_RSP\x10\xa1\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENOTIFICATIONCOMMANDID']._serialized_start=1065
  _globals['_ENOTIFICATIONCOMMANDID']._serialized_end=1213
  _globals['_NOTIFICATIONWHITELISTCTRL']._serialized_start=66
  _globals['_NOTIFICATIONWHITELISTCTRL']._serialized_end=174
  _globals['_NOTIFICATIONCOMMRSP']._serialized_start=177
  _globals['_NOTIFICATIONCOMMRSP']._serialized_end=326
  _globals['_NOTIFICATIONIOS']._serialized_start=328
  _globals['_NOTIFICATIONIOS']._serialized_end=436
  _globals['_NOTIFICATIONCONTROL']._serialized_start=439
  _globals['_NOTIFICATIONCONTROL']._serialized_end=606
  _globals['_NOTIFICATIONDATAPACKAGE']._serialized_start=609
  _globals['_NOTIFICATIONDATAPACKAGE']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
