# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onboarding.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'onboarding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10onboarding.proto\x12\x1a\x65ven_connect.g2.onboarding\x1a\x0c\x63ommon.proto\"\x99\x01\n\x0fOnboardingEvent\x12;\n\x05\x65vent\x18\x01 \x01(\x0e\x32,.even_connect.g2.onboarding.eOnboardingEvent\x12\x12\n\neventParam\x18\x02 \x01(\x05\x12\x35\n\terrorCode\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"L\n\x13OnboardingHeartbeat\x12\x35\n\terrorCode\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\x8e\x01\n\x10OnboardingConfig\x12\x43\n\tprocessId\x18\x01 \x01(\x0e\x32\x30.even_connect.g2.onboarding.eOnboardingProcessId\x12\x35\n\terrorCode\x18\x02 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xe1\x02\n\x15OnboardingDataPackage\x12\x43\n\tcommandId\x18\x01 \x01(\x0e\x32\x30.even_connect.g2.onboarding.eOnboardingCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x41\n\x06\x63onfig\x18\x03 \x01(\x0b\x32,.even_connect.g2.onboarding.OnboardingConfigH\x00\x88\x01\x01\x12G\n\theartbeat\x18\x04 \x01(\x0b\x32/.even_connect.g2.onboarding.OnboardingHeartbeatH\x01\x88\x01\x01\x12?\n\x05\x65vent\x18\x05 \x01(\x0b\x32+.even_connect.g2.onboarding.OnboardingEventH\x02\x88\x01\x01\x42\t\n\x07_configB\x0c\n\n_heartbeatB\x08\n\x06_event*:\n\x10\x65OnboardingEvent\x12\x11\n\rUNKNOWN_EVENT\x10\x00\x12\x13\n\x0fGLS_WEAR_STATUS\x10\x01*]\n\x14\x65OnboardingProcessId\x12\x13\n\x0fUNKNOWN_PROCESS\x10\x00\x12\x0c\n\x08START_UP\x10\x01\x12\t\n\x05TOUCH\x10\x02\x12\x0b\n\x07HEAD_UP\x10\x03\x12\n\n\x06\x46INISH\x10\x04*N\n\x14\x65OnboardingCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\n\n\x06\x43ONFIG\x10\x01\x12\r\n\tHEARTBEAT\x10\x02\x12\t\n\x05\x45VENT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onboarding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EONBOARDINGEVENT']._serialized_start=797
  _globals['_EONBOARDINGEVENT']._serialized_end=855
  _globals['_EONBOARDINGPROCESSID']._serialized_start=857
  _globals['_EONBOARDINGPROCESSID']._serialized_end=950
  _globals['_EONBOARDINGCOMMANDID']._serialized_start=952
  _globals['_EONBOARDINGCOMMANDID']._serialized_end=1030
  _globals['_ONBOARDINGEVENT']._serialized_start=63
  _globals['_ONBOARDINGEVENT']._serialized_end=216
  _globals['_ONBOARDINGHEARTBEAT']._serialized_start=218
  _globals['_ONBOARDINGHEARTBEAT']._serialized_end=294
  _globals['_ONBOARDINGCONFIG']._serialized_start=297
  _globals['_ONBOARDINGCONFIG']._serialized_end=439
  _globals['_ONBOARDINGDATAPACKAGE']._serialized_start=442
  _globals['_ONBOARDINGDATAPACKAGE']._serialized_end=795
# @@protoc_insertion_point(module_scope)
