# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ota_transmit.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'ota_transmit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ota_transmit.proto\x12\x1c\x65ven_connect.g2.ota_transmit*\xc5\x02\n\x0f\x65OTATransmitRsp\x12\x18\n\x14OTA_RECV_RSP_SUCCESS\x10\x00\x12\x1b\n\x17OTA_RECV_RSP_HEADER_ERR\x10\x01\x12\x19\n\x15OTA_RECV_RSP_PATH_ERR\x10\x02\x12\x18\n\x14OTA_RECV_RSP_CRC_ERR\x10\x03\x12\x18\n\x14OTA_RECV_RSP_TIMEOUT\x10\x04\x12\x1d\n\x19OTA_RECV_RSP_NO_RESOURCES\x10\x05\x12 \n\x1cOTA_RECV_RSP_FLASH_WRITE_ERR\x10\x06\x12\x1b\n\x17OTA_RECV_RSP_CHECK_FAIL\x10\x07\x12\x19\n\x15OTA_RECV_RSP_UPDATING\x10\x08\x12\x1c\n\x18OTA_RECV_RSP_SYS_RESTART\x10\t\x12\x15\n\x11OTA_RECV_RSP_FAIL\x10\n*\x96\x01\n\x0f\x65OTATransmitCID\x12\x16\n\x12OTA_TRANSMIT_START\x10\x00\x12\x1c\n\x18OTA_TRANSMIT_INFORMATION\x10\x01\x12\x15\n\x11OTA_TRANSMIT_FILE\x10\x02\x12\x1d\n\x19OTA_TRANSMIT_RESULT_CHECK\x10\x03\x12\x17\n\x13OTA_TRANSMIT_NOTIFY\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ota_transmit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EOTATRANSMITRSP']._serialized_start=53
  _globals['_EOTATRANSMITRSP']._serialized_end=378
  _globals['_EOTATRANSMITCID']._serialized_start=381
  _globals['_EOTATRANSMITCID']._serialized_end=531
# @@protoc_insertion_point(module_scope)
