# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ring.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'ring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nring.proto\x12\x14\x65ven_connect.g2.ring\x1a\x0c\x63ommon.proto\"\xf6\x02\n\x0bRingRawData\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\x05\x12\x14\n\x0c\x63hargeStates\x18\x02 \x01(\x05\x12\n\n\x02hr\x18\x03 \x01(\x05\x12\x13\n\x0bhrTimestamp\x18\x04 \x01(\x05\x12\x0c\n\x04spo2\x18\x05 \x01(\x05\x12\x15\n\rspo2Timestamp\x18\x06 \x01(\x05\x12\x0b\n\x03hrv\x18\x07 \x01(\x05\x12\x14\n\x0chrvTimestamp\x18\x08 \x01(\x05\x12\x0c\n\x04temp\x18\t \x01(\x05\x12\x15\n\rtempTimestamp\x18\n \x01(\x05\x12\x0f\n\x07\x61\x63tKcal\x18\x0b \x01(\x05\x12\x18\n\x10\x61\x63tKcalTimestamp\x18\x0c \x01(\x05\x12\x0f\n\x07\x61llKcal\x18\r \x01(\x05\x12\x18\n\x10\x61llKcalTimestamp\x18\x0e \x01(\x05\x12\r\n\x05steps\x18\x0f \x01(\x05\x12\x16\n\x0estepsTimestamp\x18\x10 \x01(\x05\x12\x35\n\terrorCode\x18\x11 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\x9a\x01\n\tRingEvent\x12\x0f\n\x07ringMac\x18\x01 \x01(\x0c\x12\x31\n\x07\x65ventId\x18\x02 \x01(\x0e\x32 .even_connect.g2.ring.eRingEvent\x12\x12\n\neventParam\x18\x03 \x01(\x05\x12\x35\n\terrorCode\x18\x04 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xe3\x01\n\x0fRingDataPackage\x12\x37\n\tcommandId\x18\x01 \x01(\x0e\x32$.even_connect.g2.ring.eRingCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x33\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x1f.even_connect.g2.ring.RingEventH\x00\x88\x01\x01\x12\x37\n\x07rawData\x18\x04 \x01(\x0b\x32!.even_connect.g2.ring.RingRawDataH\x01\x88\x01\x01\x42\x08\n\x06_eventB\n\n\x08_rawData*,\n\neRingEvent\x12\x11\n\rUNKNOWN_EVENT\x10\x00\x12\x0b\n\x07\x42LE_ADV\x10\x01*;\n\x0e\x65RingCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x12\x0c\n\x08RAW_DATA\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERINGEVENT']._serialized_start=814
  _globals['_ERINGEVENT']._serialized_end=858
  _globals['_ERINGCOMMANDID']._serialized_start=860
  _globals['_ERINGCOMMANDID']._serialized_end=919
  _globals['_RINGRAWDATA']._serialized_start=51
  _globals['_RINGRAWDATA']._serialized_end=425
  _globals['_RINGEVENT']._serialized_start=428
  _globals['_RINGEVENT']._serialized_end=582
  _globals['_RINGDATAPACKAGE']._serialized_start=585
  _globals['_RINGDATAPACKAGE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
