# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_id_def.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'service_id_def.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14service_id_def.proto\x12\x1e\x65ven_connect.g2.service_id_def*\xbe\x07\n\x03SID\x12\x15\n\x11UI_DEFAULT_APP_ID\x10\x00\x12\"\n\x1eUI_BACKGROUND_DASHBOARD_APP_ID\x10\x01\x12\x19\n\x15UI_FOREGROUND_MEUN_ID\x10\x03\x12!\n\x1dUI_FOREGROUND_NOTIFICATION_ID\x10\x04\x12\x17\n\x13UI_TRANSLATE_APP_ID\x10\x05\x12\x18\n\x14UI_TELEPROMPT_APP_ID\x10\x06\x12\x1c\n\x18UI_FOREGROUND_EVEN_AI_ID\x10\x07\x12\x1f\n\x1bUI_BACKGROUND_NAVIGATION_ID\x10\x08\x12\x15\n\x11UI_SETTING_APP_ID\x10\t\x12\x18\n\x14UI_TRANSCRIBE_APP_ID\x10\n\x12\x18\n\x14UI_CONVERSATE_APP_ID\x10\x0b\x12\x17\n\x13UI_QUICKLIST_APP_ID\x10\x0c\x12\x1c\n\x18SERVICE_SYNC_INFO_APP_ID\x10\r\x12\x14\n\x10UI_HEALTH_APP_ID\x10\x0e\x12\x14\n\x10UI_LOGGER_APP_ID\x10\x0f\x12\x18\n\x14UI_ONBOARDING_APP_ID\x10\x10\x12#\n\x1fSERVICE_MODULE_CONFIGURE_APP_ID\x10 \x12%\n!UI_FOREGROUND_SYSTEM_ALERT_APP_ID\x10!\x12\x1e\n\x19UX_DEVICE_SETTINGS_APP_ID\x10\x80\x01\x12\x1b\n\x16UX_GLASSES_CASE_APP_ID\x10\x81\x01\x12\x18\n\x13UX_RING_ROW_DATA_ID\x10\x90\x01\x12\x1a\n\x15UX_RING_DATA_RELAY_ID\x10\x91\x01\x12\x1b\n\x16UX_OTA_TRANSMIT_CMD_ID\x10\xc0\x01\x12 \n\x1bUX_OTA_TRANSMIT_RAW_DATA_ID\x10\xc1\x01\x12\x1e\n\x19UX_OTA_EXPORT_FILE_CMD_ID\x10\xc2\x01\x12#\n\x1eUX_OTA_EXPORT_FILE_RAW_DATA_ID\x10\xc3\x01\x12%\n UX_EVEN_FILE_SERVICE_CMD_SEND_ID\x10\xc4\x01\x12*\n%UX_EVEN_FILE_SERVICE_RAW_SEND_DATA_ID\x10\xc5\x01\x12\'\n\"UX_EVEN_FILE_SERVICE_CMD_EXPORT_ID\x10\xc6\x01\x12,\n\'UX_EVEN_FILE_SERVICE_RAW_EXPORT_DATA_ID\x10\xc7\x01\x12\x17\n\x12INVALID_SERVICE_ID\x10\xff\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_id_def_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SID']._serialized_start=57
  _globals['_SID']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
