# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync_info.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'sync_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsync_info.proto\x12\x19\x65ven_connect.g2.sync_info\"\xbe\x01\n\x16sync_info_main_msg_ctx\x12>\n\x07\x63mdList\x18\x01 \x01(\x0e\x32-.even_connect.g2.sync_info.Sync_Info_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x43\n\x07\x64\x61taMsg\x18\x03 \x01(\x0b\x32-.even_connect.g2.sync_info.sync_info_data_msgH\x00\x88\x01\x01\x42\n\n\x08_dataMsg\"F\n\x12sync_info_data_msg\x12\x17\n\x0f\x62\x61\x63kgroundAppID\x18\x01 \x01(\x05\x12\x17\n\x0f\x66oregroundAppID\x18\x02 \x01(\x05*H\n\x12Sync_Info_Cmd_list\x12\x19\n\x15\x41PP_REQUEST_SYNC_INFO\x10\x00\x12\x17\n\x13OS_NOTIFY_SYNC_INFO\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNC_INFO_CMD_LIST']._serialized_start=311
  _globals['_SYNC_INFO_CMD_LIST']._serialized_end=383
  _globals['_SYNC_INFO_MAIN_MSG_CTX']._serialized_start=47
  _globals['_SYNC_INFO_MAIN_MSG_CTX']._serialized_end=237
  _globals['_SYNC_INFO_DATA_MSG']._serialized_start=239
  _globals['_SYNC_INFO_DATA_MSG']._serialized_end=309
# @@protoc_insertion_point(module_scope)
